FROM python:3.10-slim


RUN pip install --no-cache-dir mlflow boto3 psycopg2-binary gunicorn


ENV MLFLOW_PORT=5001

EXPOSE ${MLFLOW_PORT}

CMD ["sh", "-c", "\
  mlflow server \
    --backend-store-uri $BACKEND_STORE_URI \
    --default-artifact-root $ARTIFACT_ROOT \
    --host 0.0.0.0 \
    --port $MLFLOW_PORT \
"]